FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Force Streamlit to port 8080
ENV PORT 8080
EXPOSE 8080
CMD ["streamlit", "run", "app_v2.py", "--server.port", "8080", "--server.address", "0.0.0.0"]